name: Continuous Integration
# This workflow runs continuous integration tasks such as building, testing, and uploading coverage reports.

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build
        run: go build ./cmd/plex-octotuner
      - name: Run tests with coverage
        run: go test -covermode=atomic -coverprofile=coverage.out ./...
      - name: Upload coverage to Codecov
        if: ${{ !cancelled() && secrets.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          flags: unittests
          name: codecov-umbrella
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build multi-platform Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: onmomo/plex-octotuner:ci
          platforms: linux/amd64
          build-args: APP_VERSION=ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
